[build-system]
requires = ["setuptools>=66", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pr1-runzepump"
dynamic = ["version"]
requires-python = ">3.11"

dependencies=[
  "runze-syringe-pump"
]

[project.entry-points."pr1.units"]
runzepump = "pr1_runzepump"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"pr1_runzepump.client" = ["*"]

[tool.setuptools_scm]
root = "../.."
